language: ruby
sudo: false
rvm:
  - 2.2.2

addons:
  postgresql: "9.3"

env:
  - RACK_ENV=test DATABASE_URL=postgresql://postgres@localhost:5432/travis_ci_test ROOT_URI=http://greeting.sucretown.net

before_script:
  - psql -U postgres -c 'CREATE DATABASE travis_ci_test'
  - bundle exec rake db:schema:apply

script:
  - bundle exec rake test

notifications:
  email:
    recipients:
      - mono@monoweb.info
    on_success: change
    on_failure: always
