language: ruby
sudo: false
rvm:
- 2.3.1
addons:
  postgresql: '9.3'
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler
env:
- RACK_ENV=test DATABASE_URL=postgresql://postgres@localhost:5432/travis_ci_test ROOT_URI=http://greeting.sucretown.net
before_script:
- psql -U postgres -c 'CREATE DATABASE travis_ci_test'
- bundle exec rake db:schema:apply
script:
- bundle exec rake test
notifications:
  slack:
    secure: boC42wRfZElNcpO95BHScYmHwGptKLG1ynH/lzTmN9TauFpSsC/hLWoeLtmzRkSH+k/qWFu8bzrpm/vr9HEoeHhFtHgrCL9HX8EL9grm0fsG3tH9qFUymNwq0kpBPjoOkXsTHJM+VaEOXn+TfYI6s+IA719Z0zxk4kkg02rg4O1EbvknoI+2R6pmUkpeZhVXGvysAMECda7VEtXYYJ6luU47Aj3Lo4D2U1EtprFQw0JeQvLEaHxzVvVyPfCv9rSKR0FhUj9lhlBPEKx8pg+rARcWmVRagkl7cqaHyBO3HYsmYyg2rLzxnQ8oqhHz2fG/yHvUssoiOh7YTkdSjcT7TQJDJADKhO8PfqCjprNbHxZ6/5z/9SMNCulV+UawUxXDDBnArR4zbwBaGZ9XlLV7CLyToWf9i+o7MCnYyukqVpVDftHcgX5IFXVhQ5hodHWssbZG209yF3DVONdHqUMkJah6FTMREXPoTf1avomMQpM6j29IlULg58CI9IzLw5+yuIAyO0cO0Sar1lLr3ro9tOTG1mrOPLEVZmAM8lQQX4Cg1Igx1YQZTXZYB97GdQgw4jYmdKZ450H2CdK2BYu0HcdYpJgH/SsFT+PqkCOq8CU6nogRjKS3WX0BI80NJIrii/FBBcwQQD4+PtCN9sYQ+iZFgeF1+sQ7g5XfazO/VBg=
    on_success: change
    on_failure: always
